#!/bin/bash
# This script connects to a server using ssh with a private key

# Set the server IP address
server_ip="18.206.208.180"

# Set the private key file
private_key="~/.ssh/school"

# Set the username
username="ubuntu"

# Use ssh with single-character flags to connect to the server
ssh -i "$private_key" "$username"@"$server_ip"

